version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
