version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'uvicorn src.main:app --host 0.0.0.0 --port 8000'
    restart: always
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - SECRET_KEY=4bd037cebda1f8b35517b3d178a3363a012445dd281f6e0f704b1a9620dc4637
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - OPENWEATHERMAP_API_KEY=
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  postgres_data:
